version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_SUPABASE_URL=https://mepvrcbidodjjgqvbcmi.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY=sb_publishable_G7fQNIkyd1EsbjrH1xwGAQ_7v3xMV6i
    restart: unless-stopped
